### PR TITLE
fix: invite modal display on android not taking up whole screen height

### LINKED ISSUE #2852: Green colored line is seen on send invite page when user A is trying to send invite to User B
**Frequency :** 100%

**Repro on build version:** Android Alfajores build V 1.40.0
**Repro on device version :** Google Pixel 2XL(11.0), Google Pixel 4a(12.0)

**Does not Repro on build version :** iOS Alfajores build V 1.40.0
**Does not Repro on device version :** iPhone 12(14.7.1), iPhone 13 mini(15.1.1)

**Pre-condition:**
1] User A must have downloaded the alfajores build
2] User A must have completed onboarding flow
3] User A must be on homepage 

**Repro Steps :**
1] Tap on send button 
2] enter a valid number / select a valid contact (non valora user)
3] it will redirect to enter amount page with loader seen on review page 
4] User A will be redirected to send invite page 

**Bug :** Green colored line is seen on send invite page

**Expected Behavior :** Send invite page should be seen properly as compared with iOS 

**Investigation**:

- For Android 12 platform user is able to see Review button on Send invite page when User A is trying to send invite to User B. [Android 12.jpg](https://drive.google.com/file/d/1Xa_cKpVmHppOFBPLgdCdvHj2UZd4H8Q8/view?usp=sharing)

**Attachment :** [android .jpg](https://drive.google.com/file/d/1rcXQrmh0xPKBIE_aZuPyLj3x2X1_RYCM/view?usp=sharing)
[iOS.jpg](https://drive.google.com/file/d/1PVJSR2wCPFg3Ebd9GGoiygq_hwUaluhh/view?usp=sharing)

### PR DESCRIPTION
**Pull request by kathaypacific**
### Description

As the title says

### Other changes

Vertical padding on the NFT banner. Before -> after

Simulator Screen Shot - iPhone 11 - 2022-09-12 at 15 50 55

Simulator Screen Shot - iPhone 11 - 2022-09-12 at 15 49 46

### Tested
Manually
### How others should test

Verify that https://github.com/valora-inc/wallet/issues/2852 cannot be reproduced.

### Related issues

- Fixes #2852 

### Backwards compatibility

Yes

### CODE REVIEW

File: src/components/InviteOptionsModal.tsx [hunk 1]
```diff
@@ -63,13 +63,15 @@ const InviteOptionsModal = ({ recipient, onClose }: Props) => {
     </SafeAreaView>
   )
 }
+const { height, width } = Dimensions.get('window')
 
 const styles = StyleSheet.create({
   container: {
-    height: variables.height,
```
Comment (kathaypacific) [inline src/components/InviteOptionsModal.tsx:69]: not sure why `variables.height` didn't work well here, from observation it looks like the `variables.height` value also accounted for a notch when the device doesn't have one so it was too short :/ the only other place that uses `variables.height` is the FullscreenCTA but the way that is used is different (not inside absolutely positioned containers)

**Review by jeanregisser — APPROVED** [review]
LGTM 👍 

Looks like the `variable.height` logic with the status height is obsolete on Andoird.

File: src/components/InviteOptionsModal.tsx [hunk 2]
```diff
@@ -63,13 +63,15 @@ const InviteOptionsModal = ({ recipient, onClose }: Props) => {
...
-    width: variables.width,
+    height,
+    width,
     flex: 1,
```
Comment (MuckT) [inline src/components/InviteOptionsModal.tsx:72]: `flexGrow: 1` and and inline styles on the the touchable seem to fix the display issues for me!
```
<Touchable onPress={handleClose} borderless={true} hitSlop={variables.iconHitslop} style={{ paddingHorizontal: variables.contentPadding }}>
  <Times />
</Touchable>
```

Comment (MuckT) [reply src/components/InviteOptionsModal.tsx:72]: @kathaypacific please disregard this has the same issue as seen in the screenshot on the top of the modal.

Comment (kathaypacific) [reply src/components/InviteOptionsModal.tsx:72]: i think that the problem you observe is with the Send amount screen, instead of with this modal. it's not expected that a modal should cover / infringe on the status bar, however you can see in the screenshot that the send amount screen header is encroaching, which is why it's peeping through. i'll see if i can fix that header instead.

Screenshot_20220913-152546_Alfajores (dev)

Comment (kathaypacific) [reply src/components/InviteOptionsModal.tsx:72]: @MuckT i'll merge this PR now and create a follow up to address the header issue since it is not strictly related to this modal. i started making some changes to the header but it was not a trivial change since it affects a few screens so a separate PR would be easier to review anyway :)

**Comment by ValoraQA** [comment]
Hey @MuckT, We have verified above issue on Latest Android Internal Release Build V1.41.0 & Test Flight Release Build V1.41.0 and updated status in test rails.

**Observations**:
- User is not able to see green colored line when user A is trying to send invite to User B and also user is not able to see review button on send invite link page 

**Test rail link:**
**Android 10:** https://valoraapp.testrail.io/index.php?/tests/view/74597
**Android 12:** https://valoraapp.testrail.io/index.php?/tests/view/74628
**iOS 12:** https://valoraapp.testrail.io/index.php?/tests/view/74659

**Devices**: Google Pixel 4a (12.0), Galaxy M31(10.0), iPhone 6+(12.5.5)

**CC**: @kathaypacific 

Thanks..!!
