### PR TITLE
fix: add a loader while the bank accounts are loading

### LINKED ISSUE #2109: [M2] BankAccounts Screen should have a loading indicator
Currently the BankAccounts screen (where all of your linked accounts are listed) does not have a loading indicator while the API is being called.

AC:
* Add a loading indicator to the BankAccounts screen while IHL is being called

### PR DESCRIPTION
**Pull request by lisaqyli**
### Description
Adding a loader when request to fetch bank accounts is inflight
Fixes #2109 

### Tested
unit tested

### CODE REVIEW

File: packages/mobile/src/account/BankAccounts.tsx [hunk 1]
```diff
@@ -43,6 +51,7 @@ function BankAccounts({ navigation, route }: Props) {
   const [isOptionsVisible, setIsOptionsVisible] = useState(false)
   const [selectedBankId, setSelectedBankId] = useState(0)
   const walletAddress = useSelector(walletAddressSelector)
+  const [isLoadingBankAccounts, setIsLoadingBankAccounts] = useState(false)
```
Comment (jh2oman) [inline packages/mobile/src/account/BankAccounts.tsx:54]: Check out the [react-async-hook docs ](https://www.npmjs.com/package/react-async-hook). It comes with loading built in and would probably be a lot cleaner than adding in new state

File: packages/mobile/src/account/BankAccounts.test.tsx [hunk 2]
```diff
@@ -89,6 +89,17 @@ describe('BankAccounts', () => {
...
+  it('shows a loading circle when getFinclusiveBankAccounts is inflight', async () => {
+    const { getByTestId, queryByTestId } = render(
+      <Provider store={store}>
+        <BankAccounts {...mockScreenProps} />
+      </Provider>
+    )
+
+    expect(getByTestId('Loader')).toBeTruthy()
+    await waitFor(() => expect(getFinclusiveBankAccounts).toHaveBeenCalled())
+    await waitFor(() => expect(queryByTestId('Loader')).toBeFalsy())
```
Comment (cajubelt) [inline packages/mobile/src/account/BankAccounts.test.tsx:101]: if you added an assertion that `AddAccount` is visible here it would probly bring the patch coverage up to where it's supposed to be

File: packages/mobile/src/account/BankAccounts.tsx (hunk 1 above)
Comment (lisaqyli) [reply packages/mobile/src/account/BankAccounts.tsx]: oh did not know about this, good suggestion

**Review by jh2oman — APPROVED** [review]

**Review by cajubelt — APPROVED** [review]
