### PR TITLE
fixing create account steps

### LINKED ISSUE #394: User not able to see 3 of 5 step after proceeding from 2 of 5 while creating account.
**Frequency:** 100%
**Repro on Devices:** iPhone 6+ (12.4.5), Vivo V11 (10), one plus 6T (10)
**Repro on build version:** Android internal build V1.14.2, Test Flight V 1.14.2(61) Android internal build V1.14.0 (1004294350) , Test Flight build V1.14.0(58), Play Store build V1.13.1

**Repro Steps:**

1. Launch the application and complete education
2. Tap on create new account 
3. Add name [User should able to see 1 o0 5 in add photo page]
4. Tap on Next button
5. Enter pin page should show [2of5 is shown in enter pin page]
6. Enter valid pin 
7. Observed that, 
**Actual Result:** 4 of 5 step is shown on phone number page 
**Expected Result:** 3 of 5 should show on second time entering pin
**Observation:** .User is able to see all pages while restoring accounts
**Attachment:** 
[CreateNewAccount.MP4](https://drive.google.com/file/d/15voJo0RfX3YciQ_-0IIr1otZqNeG66UB/view?usp=sharing)
[RestoreAccount.MP4](https://drive.google.com/file/d/17blGdGULGRoyWylYjrNaNyzW_D9YAnMp/view?usp=sharing )

### PR DESCRIPTION
**Pull request by lisaqyli**
### Description
Create new account flow has a total of 3 onboarding steps while restoring account has an additional onboarding step of importing the wallet. Therefore, fixing the title of the onboarding flow. 

### Tested

Manually tested, see screenshot attached

### Related issues

- Fixes #394

### CODE REVIEW

**Comment by lisaqyli** [comment]
create account name and profile
restore account name and profile
)

File: packages/mobile/src/verify/VerificationInputScreen.tsx [hunk 1]
```diff
@@ -115,7 +117,7 @@ function HeaderLeftButton() {
 }
 
 class VerificationInputScreen extends React.Component<Props, State> {
-  static navigationOptions = ({ navigation }: ScreenProps) => ({
+  static navigationOptions = ({ navigation, route }: ScreenProps) => ({
```
Comment (tarikbellamine) [inline packages/mobile/src/verify/VerificationInputScreen.tsx:120]: I think it's unnecessary to use `route` here if you already have `chouseToRestoreAccount` in state

**Review by tarikbellamine — CHANGES_REQUESTED** [review]
Nice work!

My only issue here is that we are using both navigation props and Redux state to store the boolean value of `choseToRestoreAccount`. IMO it's unnecessary to also pass the variable through navigation props if it already exists in state.

I think a pattern that may be helpful is pulling from state then using `navigation.setParams` so that value is available in the header component. Oftentimes the best place to do this is in `componentDidMount`.

You can check out `VerificationInputScreen.tsx` as an example of how to use `navigation.setParams`

File: packages/mobile/src/verify/VerificationEducationScreen.tsx [hunk 2]
```diff
@@ -151,6 +152,10 @@ function VerificationEducationScreen({ route, navigation }: Props) {
     }
   }, [route.params?.selectedCountryCodeAlpha2])
 
+  useEffect(() => {
```
Comment (tarikbellamine) [inline packages/mobile/src/verify/VerificationEducationScreen.tsx:155]: Nice!

File: packages/mobile/src/verify/VerificationLoadingScreen.tsx [hunk 3]
```diff
@@ -46,14 +46,15 @@ const mapStateToProps = (state: RootState) => {
     verificationStatus: state.identity.verificationStatus,
     retryWithForno: state.account.retryVerificationWithForno,
     fornoMode: state.web3.fornoMode,
+    choseToRestoreAccount: state.account.choseToRestoreAccount,
```
Comment (tarikbellamine) [inline packages/mobile/src/verify/VerificationLoadingScreen.tsx:49]: I don't think we need any changes to this file anymore :)

**Review by tarikbellamine — COMMENTED** [review]
Nice work!

**Review by tarikbellamine — APPROVED** [review]
🔥

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this task using Latest Android Internal build V1.20.2, Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tools.

**Android(10):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516235
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516236

**iOS (14):**
Case1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516251
Case2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516252

**Devices:** iPhone 12 (14.7.1), Redmi Note 8 (10.0)

**Comment by ValoraQA** [comment]
Hi @MuckT  we have verified this issue on latest Android internal build V1.20.2 and updated the status in Testquality tool link .
**Test Qulaity tool link :**
**Link 1 :** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516235
**Link 2 :** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516236

**Verified On Devices:** Redmi Note 8 (9.0)

CC: @lisaqyli

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Android Internal build V1.20.2 & Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
Test Quality Tool Link:

Android(11):
Case 1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516231
Case 2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516232

Android (8):
Case 1: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516243
Case 2: https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516244

Verified on Devices : OnePlus 7T (11.0) , Samsung Galaxy J5 (8.0)
CC: @lisaqyli

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest  Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
**Test Quality Tool Link:**
**iOS(13.0)**
- https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516247
**Verified On Devices:** iPhone Xs Max(13.5.1)

**Comment by ValoraQA** [comment]
Hey @MuckT , We have verified this issue using Latest Test flight build 1.20.2 (1632859153) & updated the status in Test Quality Tool.
Test Quality Tool Link:
**iOS(15.0):**
**Case1:** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516255
**Case2:** https://valora.testquality.com/project/12128/plan/21930/run/150772/result/2516256

**Devices:** iPhone 12(15.0)
CC: @lisaqyli
