### PR TITLE
Fix fee estimation issue when sending through a deep link

### LINKED ISSUE #1911: Fix payment by deeplink issue reported by Kotani Pay

### PR DESCRIPTION
**Pull request by gnardini**
### Description

If a user opens a payments deeplink they get directed straight to the `SendConfirmation` screen and therefore they didn't have a fee estimation, so the Send button wasn't clickable.

This PR makes it so that the fee estimation is made if it's not already in the Redux store.

### Other changes

N/A

### Tested

Manually

### How others should test

- On a fresh install, open a deep link like `celo://wallet/pay?address=0xB2539a7dcc69a0B28c7Ca73f1D2FF06b9d59E5b9&displayName=Test&currencyCode=KES&amount=0.1`
- See that you can send correctly.

### Related issues

- Fixes #1911

### Backwards compatibility

N/A

### CODE REVIEW

File: packages/mobile/src/send/SendConfirmation.tsx [hunk 1]
```diff
@@ -141,9 +141,13 @@ function SendConfirmation(props: Props) {
 
   const isInvite = !recipient.address
   const feeEstimates = useSelector(feeEstimatesSelector)
-  const feeEstimate = feeEstimates[tokenAddress]?.[isInvite ? FeeType.INVITE : FeeType.SEND]
+  const feeType = isInvite ? FeeType.INVITE : FeeType.SEND
+  const feeEstimate = feeEstimates[tokenAddress]?.[feeType]
 
   useEffect(() => {
+    if (!feeEstimate) {
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendConfirmation.tsx:148]: `feeEstimate` should be part of the effect dependencies.
And in a separate effect otherwise it may trigger the dispatch too many times.

**Review by jeanregisser — COMMENTED** [review]
Thanks! Would be great to cover this with a test.
One bug -> one test to make sure it doesn't come back.

**Comment by MuckT** [comment]
I've been unable to reproduce this in e2e test. I've attempted to clear the redux store by uninstalling and reinstalling, but I am still able to send to the deep link provided in the example after completing the restore flow.

File: packages/mobile/src/send/SendConfirmation.tsx (hunk 1 above)
Comment (gnardini) [reply packages/mobile/src/send/SendConfirmation.tsx:148]: Moved it to its own `useEffect` since it could have been triggered more than once regardless by sharing the `useEffect` with the dek register estimation

**Comment by gnardini** [comment]
> Thanks! Would be great to cover this with a test.

Thanks for keeping me accountable :)

File: packages/mobile/src/send/SendConfirmation.tsx [hunk 2]
```diff
@@ -141,13 +141,20 @@ function SendConfirmation(props: Props) {
...
+      dispatch(estimateFee({ feeType, tokenAddress }))
+    }
+  }, [feeEstimate])
 
   useEffect(() => {
     if (!isDekRegistered) {
       dispatch(estimateFee({ feeType: FeeType.REGISTER_DEK, tokenAddress }))
     }
-  }, [isDekRegistered])
+  }, [isDekRegistered, feeEstimate])
```
Comment (jeanregisser) [inline packages/mobile/src/send/SendConfirmation.tsx:157]:
```suggestion
  }, [isDekRegistered])
```

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified the above issue in latest android internal release build and latest iOS testflight release build V:1.25.2 and observed that : User is redirected to homepage after selecting valora application via deep link

**refer attachment** : [kotanipay.mp4](https://drive.google.com/file/d/1IG4_KEal4LZOwK_kdVCMXZwGWbSd_UMn/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue in latest Android internal release build V:1.25.2 and latest iOS testflight build V:1.25.2 and updated the status in test rails

**Android 11:**
https://valoraapp.testrail.io/index.php?/tests/view/7426&group_by=cases:section_id&group_order=asc&group_id=33

**iOS 14 :**
https://valoraapp.testrail.io/index.php?/tests/view/7411&group_by=cases:section_id&group_order=asc&group_id=33

**Observation :** User is redirected to homepage instead of send amount page after performing deep link flow [bug](https://github.com/valora-inc/wallet/issues/1940)

**Devices :** Google Pixel 2XL(11.), iPhone 12(14.7.1)

**CC:** @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in latest Android internal release build V:1.25.2 and updated the status in test rails

**Android 8:**

https://valoraapp.testrail.io/index.php?/tests/view/7504&group_by=cases:section_id&group_order=asc&group_id=33



**Observation :** User is redirected to homepage instead of send amount page after performing deep link flow and here is the link for [bug](https://github.com/valora-inc/wallet/issues/1940)

**Devices :** Samsung Galaxy J5 Prime(8.0.0)

CC: @gnardini

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above task in latest Android internal release build and latest iOS Testflight build V:1.25.2 & updated the status in test rails

**Android 10:**

https://valoraapp.testrail.io/index.php?/tests/view/7519&group_by=cases:section_id&group_order=asc&group_id=33

**iOS 13:**
https://valoraapp.testrail.io/index.php?/tests/view/7534&group_by=cases:section_id&group_order=asc&group_id=33

**Observation** : User is redirected to homepage instead of send amount page after performing deep link flow and here is the link for [bug](https://github.com/valora-inc/wallet/issues/1940) for it.

**Devices** : Samsung Galaxy M40(10.0), iPhone 7(13.3)

**CC:** @gnardini
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in latest Android internal release build V:1.25.2 and updated the status in test rails. User is redirected to homepage instead of send amount page after performing deep link flow, we have raised a bug.

**Test rail link:**
**Android 9:** https://valoraapp.testrail.io/index.php?/tests/view/7549

**Bug:** [Link](https://github.com/valora-inc/wallet/issues/1940)
**Devices :** Redmi Note 5 pro (9.0)
CC: @gnardini
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT, we have verified the above task in latest Test flight release build V:1.25.2 and updated the status in test rails. User is redirected to homepage instead of send amount page after performing deep link flow, we have raised a bug.

**Test rail link:**
**iOS 15:** https://valoraapp.testrail.io/index.php?/tests/view/7564

**Bug:** [Link](https://github.com/valora-inc/wallet/issues/1940)
**Devices :** iPhone 13 mini (15.1.1)
CC: @gnardini
Thanks..!!
